### ISSUE TITLE
Due to the use of reflect.Value.Call, the binary size is huge

### ISSUE THREAD

**Issue by electricface** [godbus/dbus#206]
Due to the use of this Call method, dead code elimination does not take effect.

**Comment by jsouthworth** [comment]
This is fairly fundamental to how this library works. It is not clear how one would implement the desired functionality without this. It may be worth investigating how to split the library up into a high level library that has the functionallity of this one and a low level library that allows one to avoid things like reflect.Call.

Does replacing the default handler with something that works another way avoid the issue?

**Comment by jhenstridge** [comment]
This probably isn't fixable without an API break.  If an API break was on the table, I'd consider changing the Handler interface to something simple like this:

```go
type Handler interface {
        HandleMethod(ctx context.Context, msg *Message) *Message
}
```

This would act similar to `net/http`'s `Handler` interface, in that it would be called in its own goroutine and be expected to handle the call synchronously.

Again like `net/http`, a multiplexer implementation of the interface would be provided that could delegate to sub-handlers based on object path, or perhaps (object path, interface).

The existing `reflect.Value.Call` behaviour is still really useful, so it would make sense to provide that as a handler that delegates method calls to some `interface{}` value it wraps.  Alternatively, you could have a handler that wraps a callable (e.g. function or bound method), and rely on a multiplexer to delegate each method exposed at the given object path.

Such a system would also allow for a stub generation to avoid use of reflect, if that's important to people.

While it might be possible to migrate to something like this with an adapter for the old handler interface.  The code bloat is unlikely to go away while `dbus.newConn` includes code to create a `defaultHandler` (in theory the call could be eliminated as dead code, but that would require the compiler to fully unwrap and inline the `ConnOption` abstraction.

**Comment by jsouthworth** [comment]
I wonder if we should create a low level version of the library as a subpackage that contains the bare minimum functionality to connect to the bus, send and receive messages, etc. Then build the existing functionality on top of the public interface for this simpler library. That way folks that just want the low level functionality can easily just use that and folks that want all the bells and whistles can use the existing library.

Anyone here interested in proposing what that interface would look like or working on that?

**Comment by jhenstridge** [comment]
I don't think separate sub-packages are necessary to fix the code bloat issue: I'd assume that if the linker can prove the function/method containing the `reflect.Value.Call` call is unused, then presumably that will allow all the other unused code to be eliminated.  Maybe the fancy reflection based export code could be split at some point in the future, but should be done on its own merits.

If we did want to move in this direction, here's one possible path forward:

1. Define a new handler interface parallel to the existing one.  It could even be private to start.
2. Write an adapter that implements the new interface as a wrapper around the old one.  This would likely reuse existing code that calls the old handler.
3. Update `dbus.Conn` to wrap the handler in the adapter, and use the new interface to dispatch incoming method call messages.
4. Update methods like `dbus.Conn.Export` to check whether the handler is the adapter type, and delegate through to methods on it.
5. Start work on implementations of the new handler interface, including a multiplexer and a reflection based object exporter.
6. Consider embedding the multiplexer in the adapter type from (2), so people can mix the new and old method of exporting objects.  Maybe mark the old `dbus.Conn.Export*` methods as deprecated.
7. When ready, bump the package major version and drop the handler interface and adapter code, and make the multiplexer type the default handler for the shared session/system connections.

**Comment by jsouthworth** [comment]
This mostly sounds good. I don't understand how the existing handler interface is the problem here. I do understand the desire for a simpler mechanism, but what is the harm in having the two interoperate instead of introducing a breaking change?

**Comment by electricface** [comment]
In go 1.15.5 version, this problem has been solved.

At present, only exporting with the Conn.Export method will have the problem of code bloat.

**Comment by electricface** [comment]
In the golang/go project, this problem was fixed in this commit.

```
commit b0da26a668fd6d4e351a00ca76695c5a233e84a2 (HEAD, refs/bisect/bad)
Author: Cherry Zhang <cherryyz@google.com>
Date:   Fri Apr 17 20:41:59 2020 -0400

    cmd/link: stop checking reflect.Value.Call in deadcode pass

    In the linker's deadcode pass, we need to keep a method live if
    it can be reached through reflection. We do this by marking all
    exported method live if reflect.Value.Method or
    reflect.Type.Method is used. Currently we also check for
    reflect.Value.Call, which is unnecessary because in order to call
    a method through reflection, the method must be obtained through
    reflect.Value.Method or reflect.Type.Method, which we already
    check.

    Per discussion in https://groups.google.com/d/msg/golang-dev/eG9It63-Bxg/_bnoVy-eAwAJ
    Thanks Brad, Russ, and Ian for bringing this up.

    Change-Id: I8e9529a224bb898dbf5752674cc9d155db386c14
    Reviewed-on: https://go-review.googlesource.com/c/go/+/228792
    Reviewed-by: Brad Fitzpatrick <bradfitz@golang.org>
```

**Comment by kolyshkin** [comment]
This is still an issue though, due to use of `Method` in export.go (`getMethods`, `getAllMethods`) and perhaps something else as well. Maybe this needs to be reopened, or a new issue files. What do you think @guelfey?

**Comment by guelfey** [comment]
Generally I agree with @jhenstridge and @jsouthworth here - avoiding this would mean a breaking change, and in that case I would prefer to do a larger restructuring of the API that more clearly separates the "low-level" parts (protocol handling, message decoding/encoding) from the "high-level", mostly reflection-based layer that I originally put on top to make this library easy to use. Realistically I don't have the time anymore to drive forward such a large change, and even then I doubt that there are so many practical issues with the current API design that it would be worth it. I labelled this with `breaking change` though under which I'm collecting issues that would require a breaking change to (properly) fix.

If I understand it correctly though, the binary size is only that large if a binary actually uses the `(*Conn).Export` method? And this is pretty much explicitly reflection-based. If you only implement a "client" (only call methods and don't export objects) you don't need to use this method, and even for exporting, `ExportMethodTable` is an alternative that works without `reflect.Method`; so in both cases the binary size should not explode
